Oefimenko
nonkor/Betlab-ruby-courses pull request #27
Opened 2016-10-15 12:40 UTC by oefimenko

Hometask 5

2016-11-04 11:15 UTC, nonkor requested changes
What can I say... As always - awesome.
But, please, look at my remarks. And one more thing - rebase our branch with latest `master` and move current hometask to _lesson6_ dir.  I see task4 here, but I suppose it's already in `master`.

2016-11-04 11:15 UTC, nonkor commented on lesson5/hometask_oefimenko/person.rb
> +      def initialize(label, block)
Why are you managing `block` here as a regular variable, not a block object?

2016-11-04 11:15 UTC, nonkor commented on lesson5/hometask_oefimenko/person.rb
> +      Dir.mkdir(PATH_TO_SERIALIZED) unless File.exists?(PATH_TO_SERIALIZED)
Nice trick, I like it!
One thing which I would improve: set some related path to current dir as default, not project root.
like `PATH_TO_SERIALIZED = __dir__ + '/serialized'`

2016-11-04 11:15 UTC, nonkor commented on lesson5/hometask_oefimenko/person.rb
> +      def fullname(name = '')
mmm... not sure that's the best idea to combine a reader and a writer in the same context.
I can call `Person.nonkor.age(10)` and it will reassign _age_ for `nonkor`. Definitely unexpected behavior. And this approach produces some dirty tricks like with `number = -1` which makes sense to avoid.

I understand your goal, but I believe it would be better to spread a responsibility of these methods (perhaps to different classes). I mean `#sex`, `#age` like constructor methods from factories and `#sex`, `#age` as readers for `Person` (or `PersonBase` in your case).

2016-11-04 11:15 UTC, nonkor commented on lesson5/hometask_oefimenko/person.rb
> +        text =  "Full Name : #{@fullname}\n"
why not
```ruby
        <<-EOF
Full Name: #{@fullname}
Age      : #{@age}
Sex      : #{@sex}
        EOF
```
?

You don't like such style, do you?

2016-11-10 09:05 UTC, oefimenko commented on lesson5/hometask_oefimenko/person.rb
> +      def initialize(label, block)
PersonBase constructor is not supposed to be called from outside of DSL, so Person module method :person already transform block to proc and pass it as an object

2016-11-10 09:16 UTC, oefimenko commented on lesson5/hometask_oefimenko/person.rb
> +        text =  "Full Name : #{@fullname}\n"
To be honest - not really. I'm became to worry about file formating.

2016-11-10 09:18 UTC, oefimenko commented on lesson5/hometask_oefimenko/person.rb
> +      Dir.mkdir(PATH_TO_SERIALIZED) unless File.exists?(PATH_TO_SERIALIZED)
Ok, I will change it.

2016-11-10 09:34 UTC, oefimenko commented on lesson5/hometask_oefimenko/person.rb
> +      def fullname(name = '')
I agree, I think it's terrible idea :) It was quick'n'dirty solution considering requested DSL.
But also I didn't want to create additional object, which would be just a proxy between #sex, #age and #sex=, #age= methods. 
But probably there are not so many options. I'll think on it a little bit.

2016-11-10 11:22 UTC, nonkor commented on lesson5/hometask_oefimenko/person.rb
> +        text =  "Full Name : #{@fullname}\n"
Ok, got it.

2017-09-26 12:35 UTC, closed without merging