add homework for method_missing
nonkor/Betlab-ruby-courses pull request #36
Opened 2016-10-27 08:54 UTC by frameq

@nonkor need review

2016-10-31 16:37 UTC, nonkor requested changes

2016-10-31 16:37 UTC, nonkor commented on lesson4/hometask_frameq.rb
> +    super.method_missing(key) unless self.key?(key)
The way how you calling `super` is incorrect. `#super` (_a method_) is not a `superclass` (_an object_).
You need to just call `super`. That's it.

2016-10-31 16:37 UTC, nonkor commented on lesson4/hometask_frameq.rb
> +    super.method_missing(key) unless self.key?(key)
And what's happened if your hash would contain a _symbol_, not a _string_? I don't think that `self.key?(key)` would handle it.

2016-10-31 16:37 UTC, nonkor commented on lesson4/hometask_frameq.rb
> +    if self[key].class == Proc
**Do not check classes in Ruby directly.**
Use `#respond_to?` whenever it's possible or `#is_a?` / `#kind_of?` if you **really** need to check class type, not allowed interface.

2016-10-31 16:37 UTC, nonkor commented on lesson4/hometask_frameq.rb
> +    self[key]
duplication with line 7.

2016-10-31 16:37 UTC, nonkor commented on lesson4/hometask_frameq.rb
> +    self[key.to_s].class == Proc ? true : false
The same as above.
And **never** wrap such simple condition to return explicitly `true` or `false`. It's redundant.
You line `self[key.to_s].class == Proc` anyway will return  `true` or `false` why you try to wrap it?

2016-11-01 15:15 UTC, frameq commented on lesson4/hometask_frameq.rb
>      key = name.to_s
Here convert $name to string. Other problems where fixed.

2016-11-01 15:37 UTC, nonkor commented on lesson4/hometask_frameq.rb
>      key = name.to_s
It's not enough. Just try to add symbol key into a hash and call it as a method.
See,
```ruby
a[:symbol_key] = 'foo'
p a.symbol_key #=> `method_missing': undefined method `symbol_key' for {:symbol_key=>1}:LazyHash (NoMethodError)
```

2016-11-01 15:40 UTC, nonkor commented on lesson4/hometask_frameq.rb
> +    super(name) unless self.key?(key)
Better to call `super` without params to [automatically forwards](http://rubylearning.com/satishtalim/ruby_overriding_methods.html) the arguments to the method of superclass.

2016-11-01 20:43 UTC, frameq commented on lesson4/hometask_frameq.rb
>      key = name.to_s
@nonkor 
If we have such hash:
```ruby
a[:symbol_key] = lambda {'i am symbol'}
a[symbol_key] = lambda {'i am string'} 
```
what should we do?

2017-09-26 12:35 UTC, closed without merging