home work lesson1
nonkor/Betlab-ruby-courses pull request #46
Opened 2016-11-12 15:50 UTC by serhiikhrychov

Home task from lesson 1 - done

2016-11-16 11:54 UTC, nonkor requested changes
Good work. Apply my suggestions, please.

2016-11-16 11:54 UTC, nonkor commented on lesson1/serhii_khrychov_hometask.rb
> +    @instance_num = @@instance_num
Don't you think that names `@instance_num` and `@@instance_num` are really confusing, do you?

2016-11-16 11:54 UTC, nonkor commented on lesson1/serhii_khrychov_hometask.rb
> +    return ":uniq" if @uniq == :uniq
Why do you wrap symbol `:uniq` into string?

2016-11-16 11:54 UTC, nonkor commented on lesson1/serhii_khrychov_hometask.rb
> +    @instance_num.even? ? ":even" : ":odd"
The same here. You can just return `:even` or `:odd` as symbols, not a strings.

2016-11-16 11:54 UTC, nonkor commented on lesson1/serhii_khrychov_hometask.rb
> +    return ":uniq" if @uniq == :uniq
Interesting decision. I thought you would use singleton method for `:uniq` instance. But your solution also works.

2016-11-16 11:54 UTC, nonkor commented on lesson1/serhii_khrychov_hometask.rb
> +instances.each {|instance| puts instance.my_instance}
Add expected output as a comments.
Like,
```ruby
# => :odd
# => :even
# and so on
```

2016-11-16 18:24 UTC, serhiikhrychov commented on lesson1/serhii_khrychov_hometask.rb
> +    return ":uniq" if @uniq == :uniq
Because we have this - "должен возвращать :even" "и :odd" in task. But I will remove it from my code

2016-11-16 19:02 UTC, serhiikhrychov commented
@nonkor code updated

2016-11-17 09:46 UTC, nonkor approved these changes
👍 
Apply small suggestions, squash commits into one and I could merge it.

2016-11-17 09:46 UTC, nonkor commented on lesson1/serhii_khrychov_hometask.rb
> +for i in 0..5
Do not use `for` in ruby at all. I forgot to write this first time, but it's a bad practice. Your case could be resolved by [#times](https://ruby-doc.org/core-2.2.0/Integer.html#method-i-times)

2016-11-17 09:46 UTC, nonkor commented on lesson1/serhii_khrychov_hometask.rb
> +
delete empty line

2016-11-20 15:11 UTC, merged

2016-11-20 15:24 UTC, nonkor commented
@serhiikhrychov why didn't you squash commits?

2016-11-20 15:29 UTC, serhiikhrychov commented
@nonkor I used "squash and merge" button

2016-11-20 15:30 UTC, serhiikhrychov commented
@nonkor I thought it should work

2016-11-20 15:30 UTC, nonkor commented
ok, it also works, sorry, I didn't saw it

2016-11-20 15:31 UTC, serhiikhrychov commented
ok. Thanks for your feedback